export enum LeaftletMapActionTypes {
  INTERACTION_END = "INTERACTION_END",
  CLEAR_BOUNDS = "CLEAR_BOUNDS",
  SELECT_LOCATION = "SELECT_LOCATION",

  ADD_REAL_ESTATE = "ADD_REAL_ESTATE",
  FIND_FROM_FILTER = "FIND_FROM_FILTER",
  TOGGLE_SHOW_ONLY_FILTER = "TOGGLE_SHOW_ONLY_FILTER"
}